workflows:
  android-workflow:
    name: Android AAB Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    scripts:
      - name: Build Android AAB Directly
        script: |
          cd yoruldum
          # İnternetten indirme yapmadan doğrudan sistemin küresel motorunu çalıştırıyoruz
          gradle bundleRelease
    artifacts:
      - yoruldum/app/build/outputs/bundle/release/*.aab
