workflows:
  android-workflow:
    name: Android AAB Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    scripts:
      - name: Setup Gradle and Build AAB
        script: |
          cd yoruldum
          # Projenin tam olarak uyumlu olduğu Gradle sürümünü buluta kuruyoruz
          gradle wrapper --gradle-version 8.9.1
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - yoruldum/app/build/outputs/bundle/release/*.aab
